# this script should not (in production) be pushed to git
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: am9l # this is base64 encoded
  mongo-root-password: d2h5QXJlWW91RGVjb2RpbmdUaGlz # this is base64 encoded
